name: Auto Assign Issue

on:
  issues:
    types: [opened]

jobs:
  assign:
    runs-on: ubuntu-latest

    steps:
      - name: Assign issue
        uses: actions/github-script@v7
        with:
          script: |
            const issue_number = context.issue.number;

            await github.rest.issues.addAssignees({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: issue_number,
              assignees: ["pavithra8867"]
            });
