name: Close Stale Issues

on:
  schedule:
    - cron: "0 0 * * *"

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v9
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          stale-issue-message: "This issue is inactive. It will be closed soon."
          close-issue-message: "Closing this issue due to inactivity."
          days-before-stale: 7
          days-before-close: 3
